services:
  go_app:
    container_name: go_app
    image: go-api
    restart: always
    env_file:
      - config/.env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    
  go_db:
    container_name: go_db
    image: go-db
    restart: always
    env_file:
      - config/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}